steps:
  #Cloning GIT repo
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/PR229/cloud-resume', 'cloned-repo']

  #Syncing with cloud storage bucket
  - name: 'gcr.io/cloud-builders/gcloud'
  + name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  + entrypoint: 'gcloud'
    args: ['gsutil', 'rsync', '-r', '/cloned-repo', 'gs://praj-resume-bucket']

options:
  logging: CLOUD_LOGGING_ONLY
