steps:
  #Cloning GIT repo
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/PR229/cloud-resume', 'cloned-repo']

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args: ['gsutil', 'rsync', '-r', '/workspace/cloned-repo', 'gs://praj-resume-bucket']

options:
  logging: CLOUD_LOGGING_ONLY
