steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/PR229/cloud-resume']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['echo', 'Running a bash command']


options:
  logging: CLOUD_LOGGING_ONLY
